### ISSUE TITLE
ToDo: Pairing code (Swiss)

### ISSUE THREAD

**Issue by almightyfoon** [almightyfoon/SwissPairingWebsite#4]
Code to generate player pairs given the following criteria:

- [ ] have not played each other (if possible)
- [ ] Are not playing the same faction (if possible)
- [ ] have the same W-L-D count
- [ ] Gather data dynamically from a json input
- [ ] Support drops
- [ ] Support byes
